{{- if and .Values.filer.enabled (not .Values.filer.auth.store.credentialsExistingSecret) (or .Values.filer.auth.store.credentials.username .Values.filer.auth.store.credentials.password) .Values.filer.configuration.store.sectionNameForConfigurationFileStoreSection .Values.filer.configuration.store.tomlContentsForConfigurationFileStoreSection }}
{{ $password := .Values.filer.auth.store.credentials.password }}
{{ $username := .Values.filer.auth.store.credentials.username }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/component: filer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "seaweedfs.name" . }}-filer-store-auth-credentials
  namespace: {{ .Release.Namespace }}
data:
  password: {{ b64enc $password }}
  username: {{ b64enc $username }}
{{- end }}
