{{- $s3Buckets := .Values.global.s3Gateway.buckets }}
{{- if and .Values.master.enabled (or .Values.filer.s3Gateway.enabled .Values.s3.enabled) $s3Buckets }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $.Release.Name }}-bucket-hook"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: {{ template "master.image" . }}
        env:
          - name: WEED_CLUSTER_DEFAULT
            value: "sw"
          - name: WEED_CLUSTER_SW_MASTER
            value: "{{ template "seaweedfs.name" . }}-master.{{ .Release.Namespace }}:9333"
          - name: WEED_CLUSTER_SW_FILER
            value: "{{ template "seaweedfs.name" . }}-filer-client.{{ .Release.Namespace }}:8888"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: SEAWEEDFS_FULLNAME
            value: "{{ template "seaweedfs.name" . }}"
        command:
          - "/bin/sh"
          - "-ec"
          - |
          {{- range $reg, $props := $s3Buckets }}
            exec /bin/echo \
            "s3.bucket.create --name {{ $props.name }}" |\
            /usr/bin/weed shell
          {{- end }}
          {{- range $reg, $props := $s3Buckets }}
          {{- if $props.anonymousRead }}
            exec /bin/echo \
            "s3.configure --user anonymous \
                --buckets {{ $props.name }} \
                --actions Read \
                --apply true" |\
                /usr/bin/weed shell
          {{- end }}  
          {{- end }}
        {{- if .Values.global.s3Gateway.auth.enabled }}
        volumeMounts:
          - name: config-users
            mountPath: /etc/sw
            readOnly: true
        {{- end }}
        ports:
          - containerPort: {{ .Values.master.configuration.ports.http }}
            name: swfs-master
          {{- if and .Values.global.monitoring.enabled .Values.master.configuration.ports.metrics }}
          - containerPort: {{ .Values.master.configuration.ports.metrics }}
            name: metrics
          {{- end }}
          - containerPort: {{ .Values.master.configuration.ports.grpc }}
            #name: swfs-master-grpc
    {{- if .Values.global.s3Gateway.auth.enabled }}
      volumes:
        - name: config-users
          secret:
            defaultMode: 420
            {{- if not (empty .Values.global.s3Gateway.auth.existingBucketUserConfigSecret) }}
            secretName: {{ .Values.global.s3Gateway.auth.existingBucketUserConfigSecret }}
            {{- else }}
            secretName: seaweedfs-s3-secret
            {{- end }}
    {{- end }}
{{- end }}
