{{- if and (or .Values.filer.s3Gateway.enabled .Values.s3.enabled) .Values.global.s3Gateway.auth.enabled }}
{{- $identities := .Values.global.s3Gateway.auth.identities }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/component: s3-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "seaweedfs.name" . }}-s3-gateway-auth-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if and $identities.administrator.enabled (not (empty (compact $identities.administrator.credentials))) }}
  administrator.credentials.json: '{{ mustToJson (compact $identities.administrator.credentials) }}'
  {{- else }}
  administrator.credentials.json: '[]'
  {{- end }}
  {{- if and $identities.guest.enabled (not (empty (compact $identities.guest.credentials))) }}
  guest.credentials.json: '{{ mustToJson (compact $identities.guest.credentials) }}'
  {{- else }}
  guest.credentials.json: '[]'
  {{- end }}
  {{- if and $identities.member.enabled (not (empty (compact $identities.member.credentials))) }}
  member.credentials.json: '{{ mustToJson (compact $identities.member.credentials) }}'
  {{- else }}
  member.credentials.json: '[]'
  {{- end }}
{{- end }}
