{{- if and (or .Values.filer.s3Gateway.enabled .Values.s3.enabled) .Values.global.s3Gateway.auth.enabled }}
{{- $administratorIdentity := "" }}
{{- if .Values.global.s3Gateway.auth.administrator.enabled }}
{{- $administratorIdentity = (dict "actions" (list "Admin" "List" "Read" "Tagging" "Write") "credentials" (.Values.global.s3Gateway.auth.administrator.credentials | compact) "name" "administrator") }}
{{- end }}
{{- $anonymousIdentity := "" }}
{{- if .Values.global.s3Gateway.auth.anonymous.enabled }}
{{- $anonymousIdentity = (dict "actions" (list "Read") "name" "anonymous") }}
{{- end }}
{{- $guestIdentity := "" }}
{{- if .Values.global.s3Gateway.auth.guest.enabled }}
{{- $guestIdentity = (dict "actions" (list "List" "Read") "credentials" (.Values.global.s3Gateway.auth.guest.credentials | compact) "name" "guest") }}
{{- end }}
{{- $memberIdentity := "" }}
{{- if .Values.global.s3Gateway.auth.member.enabled }}
{{- $memberIdentity = (dict "actions" (list "List" "Read" "Tagging" "Write") "credentials" (.Values.global.s3Gateway.auth.member.credentials | compact) "name" "member") }}
{{- end }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
  labels:
    app.kubernetes.io/component: s3-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "seaweedfs.name" . }}-s3-gateway-auth
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if and .Values.global.s3Gateway.auth.administrator.enabled .Values.global.s3Gateway.auth.administrator.credentials }}
  administratorCredentials: {{ quote (mustToJson .Values.global.s3Gateway.auth.administrator.credentials) }}
  {{- end }}
  {{- if and .Values.global.s3Gateway.auth.guest.enabled .Values.global.s3Gateway.auth.guest.credentials }}
  guestCredentials: {{ quote (mustToJson .Values.global.s3Gateway.auth.guest.credentials) }}
  {{- end }}
  {{- if and .Values.global.s3Gateway.auth.member.enabled .Values.global.s3Gateway.auth.member.credentials }}
  memberCredentials: {{ quote (mustToJson .Values.global.s3Gateway.auth.member.credentials) }}
  {{- end }}
  config.json: {{ quote (mustToJson (dict "identities" (compact (list $administratorIdentity $anonymousIdentity $guestIdentity $memberIdentity)))) }}
{{- end }}
