{{- if .Values.global.tls.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "seaweedfs.name" . }}-security-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  security.toml: |-
    # this file is read by master, volume server, and filer

    # the jwt signing key is read by master and volume server
    # a jwt expires in 10 seconds
    [jwt.signing]
    key = "{{ randAlphaNum 10 | b64enc }}"

    [grpc]
    ca = "/usr/local/share/ca-certificate/tls.crt"

    [grpc.volume]
    cert = "/usr/local/share/ca-certificate/tls.crt"
    key  = "/usr/local/share/ca-certificate/tls.key"

    [grpc.master]
    cert = "/usr/local/share/ca-certificate/tls.crt"
    key  = "/usr/local/share/ca-certificate/tls.key"

    [grpc.filer]
    cert = "/usr/local/share/ca-certificate/tls.crt"
    key  = "/usr/local/share/ca-certificate/tls.key"

    # use this for any place needs a grpc client
    # i.e., "weed backup|benchmark|filer.copy|filer.replicate|mount|s3|upload"
    [grpc.client]
    cert = "/usr/local/share/ca-certificate/tls.crt"
    key  = "/usr/local/share/ca-certificate/tls.key"

    # volume server https options
    # Note: work in progress!
    #     this does not work with other clients, e.g., "weed filer|mount" etc, yet.
    [https.client]
    enabled = false
    [https.volume]
    cert = ""
    key  = ""
{{- end }}
