{{- if .Values.s3.enabled }}
{{- $ports := .Values.master.configuration.ports }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: s3
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "seaweedfs.name" . }}-s3
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "swfs-s3"
    port: {{ .Values.global.s3Gateway.ports.http }}
    targetPort: {{ .Values.global.s3Gateway.ports.http }}
    protocol: TCP
{{- if and .Values.global.tls.enabled .Values.global.s3Gateway.ports.https }}
  - name: "swfs-s3-tls"
    port: {{ .Values.global.s3Gateway.ports.https }}
    targetPort: {{ .Values.global.s3Gateway.ports.https }}
    protocol: TCP
{{- end }}
{{- if and .Values.global.monitoring.enabled $ports.metrics }}
  - name: "metrics"
    port: {{ $ports.metrics }}
    targetPort: {{ $ports.metrics }}
    protocol: TCP
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    app.kubernetes.io/component: s3
{{- end }}