{{- if .Values.master.enabled }}
{{- $ports := .Values.master.configuration.ports }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "seaweedfs.name" . }}-master
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: "swfs-master"
    port: {{ $ports.http }}
    targetPort: {{ $ports.http }}
    protocol: TCP
  - name: "swfs-master-grpc"
    port: {{ $ports.grpc }}
    targetPort: {{ $ports.grpc }}
    protocol: TCP
  {{- if and .Values.global.monitoring.enabled $ports.metrics }}
  - name: "metrics"
    port: {{ $ports.metrics }}
    targetPort: {{ $ports.metrics }}
    protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "seaweedfs.name" . }}
    app.kubernetes.io/component: master
{{- end }}
